### ISSUE TITLE
Nettoyage nécessaire des commentaires

### ISSUE THREAD

**Issue by AlexandreGefen** [oeuvres/depub#2]
Pour éviter des erreurs de comptage notamment exemple : 

` <!-- OEBPS/Byat_9780307819598_epub_tp_r1.htm -> OEBPS/Byat_9780307819598_epub_cop_r1.htm -->`

**Comment by glorieux-f** [comment]
En quoi les commentaires peuvent produire un problème ? Ils sont au contraire précieux pour assurer qu’aucun contenu n’est perdu.

**Comment by glorieux-f** [comment]
Pas de raison donnée à ces comptages, question considérée close.
