### ISSUE TITLE
Nettoyage des pagebreak rendus en div

### ISSUE THREAD

**Issue by AlexandreGefen** [oeuvres/depub#4]
Exemple `<div rend="mbp_pagebreak" xml:id="calibre_pb_10"/>`

**Comment by glorieux-f** [comment]
Codé, ne rien sortir pour un <div> vide, pas testé, l’auteur de l’issue la referme s'il est content, ou bien passe un fichier test.

**Comment by glorieux-f** [comment]
Pas de fichier test fourni, problème considéré comme résolu.
