### ISSUE TITLE
Autres nettoyages

### ISSUE THREAD

**Issue by AlexandreGefen** [oeuvres/depub#5]
Id et xml=id : `xml:id=`

**Comment by glorieux-f** [comment]
Pas clair. Peux-tu préciser ? Tu ne veux pas les id originaux ?

**Comment by glorieux-f** [comment]
Id html supprimés, peuvent être répétés d'une page sur l'autre et produire des erreurs dans le TEI, mais cela pourra poser de gros problèmes pour les notes et autres liens.
