### ISSUE TITLE
Pages HTML dans le fil (<spine>) mais pas dans la toc

### ISSUE THREAD

**Issue by AlexandreGefen** [oeuvres/depub#6]
[Lisbonne derniere marge - Antoine Volodine.epub.zip](https://github.com/oeuvres/Debook/files/729317/Lisbonne.derniere.marge.-.Antoine.Volodine.epub.zip)

**Comment by glorieux-f** [comment]
Le XML est OK maintenant. Mais ce n’est pas le seul problème. Les seul fichiers pointés par la TOC sont les titres de parties, pas les textes.

**Comment by glorieux-f** [comment]
Implémenté.
