### ISSUE TITLE
Exemples de fichiers non convertis correctement 

### ISSUE THREAD

**Issue by AlexandreGefen** [oeuvres/depub#7]
Fichiers ne passant pas. Peu importe les titres et les années. Cf. zip +bas.

**Comment by AlexandreGefen** [comment]
[erreurs.zip](https://github.com/oeuvres/Debook/files/748041/erreurs.zip)

**Comment by glorieux-f** [comment]
R&B > R&amp;B cf. html.sed 
s@&([a-zA-Z]*\s)@&amp;$1@g # incorrect entities

**Comment by glorieux-f** [comment]
Noms de fichiers avec des espaces
Text/Parce%20que%20je%20t%27aime%20_split_006.htm
urldecode()

**Comment by glorieux-f** [comment]
Les autres problèmes viennent d’une mauvaise TOC
https://github.com/oeuvres/Debook/issues/6
