### ISSUE TITLE
toc.ncx pointing to the last file

### ISSUE THREAD

**Issue by AlexandreGefen** [oeuvres/depub#8]
[Archive.zip](https://github.com/oeuvres/Debook/files/791935/Archive.zip)
Quelques exemples de conversions ne fonctionnant toujours pas avec la dernière version du 21 février

**Comment by glorieux-f** [comment]
Bug & dans un titre de chapitre de la table des matières

**Comment by glorieux-f** [comment]
Tables des matières complètement fantaisistes qui commencent par la fin du livre. Le contournement consiste à prendre tous les fichiers qui précèdent la première entrée dans la toc, ce qui dans le cas général est plutôt mauvais (page de titre, copyright…). Garbage in > garbage out.
Epub est un très mauvais format pour la production de textes, il vaut mieux partir du traitement de textes.
