### ISSUE TITLE
Les quatre derniers pub qui plantent

### ISSUE THREAD

**Issue by AlexandreGefen** [oeuvres/depub#9]
Fichiers vides
[Quatre.zip](https://github.com/oeuvres/Debook/files/794332/Quatre.zip)

**Comment by glorieux-f** [comment]
Vraiment, il n'y en a plus que 4 ?

**Comment by AlexandreGefen** [comment]
Oui, j'ai inspecté tous les fichiers de petite taille et regardé les ePub
d'origine, si on exclut le cas d'epub fautifs ou vides (quelques cas à
simplement supprimer), tout le reste est bon

2017-02-22 10:26 GMT-08:00 Frédéric Glorieux <notifications@github.com>:

**Comment by glorieux-f** [comment]
Erreur XML quand un titre de Toc est vide
`<navPoint id="navPoint-1" playOrder="1">
            <navLabel>
                <text></text>
            </navLabel>
            <content src="Text/Titre.xhtml"/>
        </navPoint>`

**Comment by glorieux-f** [comment]
Titre de toc avec plusieurs milliers de caractères, manifestement un bug de l'export epub, Debook protégé de cette erreur, mais l'epub demanderait de toute façon nettoyage.

**Comment by glorieux-f** [comment]
Un problème de namespace 
&lt;meta xmlns="http://www.idpf.org/2007/opf" content="0.8.0" name="Sigil version"/&gt;

**Comment by glorieux-f** [comment]
Crainquebille…epub, inutilisable

**Comment by glorieux-f** [comment]
En souhaitant n’avoir rien cassé…
